### ISSUE TITLE
Error message in nba_travel

### ISSUE THREAD

**Issue by lyledanley** [josedv82/airball#6]
When running the function blank with no set arguments, the following error is called:

Error in open.connection(x, "rb") : HTTP error 404.

**Comment by josedv82** [comment]
I just recently added some functionality to prepare the package to pull 2022 schedule. The schedule has not been released yet, which means that when the function calls the website to scrap the data but the website still does not exits. 

See website below calling  2022 games throws a 404 error

https://www.basketball-reference.com/leagues/NBA_2022_games-june.html 

if you change 2022 for 2021 the website works.

I believe the new schedule will be released soon. I probably should've waited before releasing the update. Will see if I can add a fix in the next few days. 

Thanks for letting me know

**Comment by josedv82** [comment]
actually, just pushed a quick fix. if you install the new version (0.4.4) it should work.

**Comment by lyledanley** [comment]
Awesome, thanks for being so responsive!
